---
title: "Box-Cox Transformation"
author: "Nicholas Chavez"
format: 
  html:
    format:
      self-contained: True
---
# Regression Box-Cox and Reset-Test

```{r}
# Load necessary libraries
library(dplyr)
library(zoo)
```

```{r}
# load data
data(mtcars)
```

```{r}
# Fit initial linear regression model with interaction term
lm1 <- lm(mpg ~ hp*wt, data = mtcars)
summary(lm1)
```

```{r}
# Generate diagnostic plots for the initial model
plot(lm1)
```

```{r}
# Perform Box-Cox transformation to find optimal lambda
bc = boxcox(fullmodel, lambda = seq(-3,3))
best.lam = bc$x[which(bc$y==max(bc$y))]
```

```{r}
# Fit a new model using the Box-Cox transformed dependent variable
if(abs(best.lam)<0.4) {
  lm1.transformed <- lm(log(mpg) ~ hp*wt, data = mtcars)
} else {
  lm1.transformed <- lm(((mpg^best.lam - 1)/best.lam) ~ hp*wt, data = mtcars)
}
```

```{r}
# Generate diagnostic plots for the transformed model
plot(lm1.transformed)
```

```{r}
#compare model preformance
cat("Original Model - Adjusted R-squared:", summary(lm1)$adj.r.squared, "\n")
cat("Transformed Model - Adjusted R-squared:", summary(lm1.transformed)$adj.r.squared, "\n")
```

```{r}
# preform a reset test 
reset_test <- resettest(lm1.transformed, power = 2:3, type = "fitted")
```

```{r}
#print results 
print(reset_test)
```

